export interface Stock {
    name: string;
    symbol: string;
    price: number;
  }
  
  export const stocks: Stock[] = [
    { name: 'Reliance Industries', symbol: 'RELIANCE', price: 2800.50 },
    { name: 'Tata Consultancy Services', symbol: 'TCS', price: 3800.75 },
    { name: 'Infosys', symbol: 'INFY', price: 1650.25 },
    { name: 'HDFC Bank', symbol: 'HDFCBANK', price: 1700.60 },
    { name: 'ICICI Bank', symbol: 'ICICIBANK', price: 1050.30 },
    { name: 'Hindustan Unilever', symbol: 'HINDUNILVR', price: 2450.90 },
    { name: 'Kotak Mahindra Bank', symbol: 'KOTAKBANK', price: 2350.45 },
    { name: 'Larsen & Toubro', symbol: 'LT', price: 3400.20 },
    { name: 'Axis Bank', symbol: 'AXISBANK', price: 1250.80 },
    { name: 'Bajaj Finance', symbol: 'BAJFINANCE', price: 9500.00 },
    { name: 'Maruti Suzuki', symbol: 'MARUTI', price: 8500.50 },
    { name: 'Asian Paints', symbol: 'ASIANPAINT', price: 3200.75 },
    { name: 'HDFC', symbol: 'HDFC', price: 2900.00 },
    { name: 'ITC', symbol: 'ITC', price: 350.25 },
    { name: 'State Bank of India', symbol: 'SBIN', price: 650.40 },
    { name: 'Titan Company', symbol: 'TITAN', price: 3100.00 },
    { name: 'UltraTech Cement', symbol: 'ULTRACEMCO', price: 8800.00 },
    { name: 'Sun Pharmaceutical', symbol: 'SUNPHARMA', price: 1100.50 },
    { name: 'Power Grid Corporation', symbol: 'POWERGRID', price: 270.30 },
    { name: 'NTPC', symbol: 'NTPC', price: 380.75 },
    { name: 'Oil & Natural Gas Corporation', symbol: 'ONGC', price: 260.40 },
    { name: 'Bajaj Auto', symbol: 'BAJAJ-AUTO', price: 8200.00 },
    { name: 'HCL Technologies', symbol: 'HCLTECH', price: 1600.25 },
    { name: 'Wipro', symbol: 'WIPRO', price: 420.50 },
    { name: 'Tata Motors', symbol: 'TATAMOTORS', price: 700.00 },
    { name: 'Tech Mahindra', symbol: 'TECHM', price: 1300.75 },
    { name: 'Divi\'s Laboratories', symbol: 'DIVISLAB', price: 5200.00 },
    { name: 'Shree Cement', symbol: 'SHREECEM', price: 31000.00 },
    { name: 'JSW Steel', symbol: 'JSWSTEEL', price: 850.50 },
    { name: 'Tata Consumer Products', symbol: 'TATACONSUM', price: 1050.00 },
    { name: 'Tata Power', symbol: 'TATAPOWER', price: 270.25 },
    { name: 'Grasim Industries', symbol: 'GRASIM', price: 2100.50 },
    { name: 'Adani Green Energy', symbol: 'ADANIGREEN', price: 950.00 },
    { name: 'Adani Ports', symbol: 'ADANIPORTS', price: 850.75 },
    { name: 'Adani Power', symbol: 'ADANIPOWER', price: 270.00 },
    { name: 'Adani Transmission', symbol: 'ADANITRANS', price: 2600.00 },
    { name: 'Bajaj Finserv', symbol: 'BAJAJFINSV', price: 12500.00 },
    { name: 'HDFC Life Insurance', symbol: 'HDFCLIFE', price: 750.50 },
    { name: 'ICICI Lombard General Insurance', symbol: 'ICICIGI', price: 1600.00 },
    { name: 'Mahindra & Mahindra', symbol: 'M&M', price: 1250.75 },
    { name: 'Nestle India', symbol: 'NESTLEIND', price: 21000.00 },
    { name: 'SBI Life Insurance', symbol: 'SBILIFE', price: 1250.00 },
    { name: 'UPL Limited', symbol: 'UPL', price: 850.50 },
    { name: 'Zomato', symbol: 'ZOMATO', price: 120.75 }
  ];